//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmPosKurİşlem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MRTREntities : DbContext
    {
        public MRTREntities()
            : base("name=MRTREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOKASYON> LOKASYON { get; set; }
        public virtual DbSet<DOVIZ_AD> DOVIZ_AD { get; set; }
        public virtual DbSet<FINANS_DETAY> FINANS_DETAY { get; set; }
        public virtual DbSet<TCMB_KUR_CRMPOS> TCMB_KUR_CRMPOS { get; set; }
        public virtual DbSet<wwwView_Dovizlifislerdetay> wwwView_Dovizlifislerdetay { get; set; }
        public virtual DbSet<wwwView_FislerinTLDegeri> wwwView_FislerinTLDegeri { get; set; }
        public virtual DbSet<wwwView_DovizliFisler> wwwView_DovizliFisler { get; set; }
        public virtual DbSet<wwwDOVIZ_KUR> wwwDOVIZ_KUR { get; set; }
    
        public virtual ObjectResult<sp_fis_kurlu_liste_getir_Result> sp_fis_kurlu_liste_getir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fis_kurlu_liste_getir_Result>("sp_fis_kurlu_liste_getir");
        }
    
        public virtual int crmpos_fifo_stok_doviz(Nullable<long> lokasyonid)
        {
            var lokasyonidParameter = lokasyonid.HasValue ?
                new ObjectParameter("lokasyonid", lokasyonid) :
                new ObjectParameter("lokasyonid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crmpos_fifo_stok_doviz", lokasyonidParameter);
        }
    
        public virtual int testsinan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("testsinan");
        }
    
        public virtual int crmpos_fifo_stok_envanter_doviz(Nullable<long> lokasyonid)
        {
            var lokasyonidParameter = lokasyonid.HasValue ?
                new ObjectParameter("lokasyonid", lokasyonid) :
                new ObjectParameter("lokasyonid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crmpos_fifo_stok_envanter_doviz", lokasyonidParameter);
        }
    
        public virtual int crmpos_odeme_guncelle(Nullable<long> tIP, Nullable<long> iD, Nullable<decimal> tUTAR, Nullable<long> dOVIZ)
        {
            var tIPParameter = tIP.HasValue ?
                new ObjectParameter("TIP", tIP) :
                new ObjectParameter("TIP", typeof(long));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            var tUTARParameter = tUTAR.HasValue ?
                new ObjectParameter("TUTAR", tUTAR) :
                new ObjectParameter("TUTAR", typeof(decimal));
    
            var dOVIZParameter = dOVIZ.HasValue ?
                new ObjectParameter("DOVIZ", dOVIZ) :
                new ObjectParameter("DOVIZ", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crmpos_odeme_guncelle", tIPParameter, iDParameter, tUTARParameter, dOVIZParameter);
        }
    
        public virtual int crmpos_paraustu_guncelle(Nullable<long> fISID, Nullable<decimal> pRUSTU)
        {
            var fISIDParameter = fISID.HasValue ?
                new ObjectParameter("FISID", fISID) :
                new ObjectParameter("FISID", typeof(long));
    
            var pRUSTUParameter = pRUSTU.HasValue ?
                new ObjectParameter("PRUSTU", pRUSTU) :
                new ObjectParameter("PRUSTU", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crmpos_paraustu_guncelle", fISIDParameter, pRUSTUParameter);
        }
    
        public virtual int crmpos_kasa_hareketi(Nullable<long> dOVIZ, Nullable<decimal> kUR, Nullable<decimal> tUTAR, string aCIKLAMA, Nullable<System.DateTime> tARIH)
        {
            var dOVIZParameter = dOVIZ.HasValue ?
                new ObjectParameter("DOVIZ", dOVIZ) :
                new ObjectParameter("DOVIZ", typeof(long));
    
            var kURParameter = kUR.HasValue ?
                new ObjectParameter("KUR", kUR) :
                new ObjectParameter("KUR", typeof(decimal));
    
            var tUTARParameter = tUTAR.HasValue ?
                new ObjectParameter("TUTAR", tUTAR) :
                new ObjectParameter("TUTAR", typeof(decimal));
    
            var aCIKLAMAParameter = aCIKLAMA != null ?
                new ObjectParameter("ACIKLAMA", aCIKLAMA) :
                new ObjectParameter("ACIKLAMA", typeof(string));
    
            var tARIHParameter = tARIH.HasValue ?
                new ObjectParameter("TARIH", tARIH) :
                new ObjectParameter("TARIH", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("crmpos_kasa_hareketi", dOVIZParameter, kURParameter, tUTARParameter, aCIKLAMAParameter, tARIHParameter);
        }
    }
}
