//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmPosKurİşlem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINANS_DETAY
    {
        public long ID { get; set; }
        public Nullable<long> FINANS { get; set; }
        public Nullable<int> FINANS_ISLEM_TURU { get; set; }
        public Nullable<long> DOVIZ_AD { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public Nullable<long> KART_BORCLU { get; set; }
        public Nullable<long> KART_ALACAKLI { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<int> SECIM { get; set; }
        public Nullable<long> TAHSILID { get; set; }
        public Nullable<long> FIS { get; set; }
        public Nullable<System.DateTime> VADE_TARIHI { get; set; }
        public Nullable<long> FK_PERSONEL { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> TAKSIT_SAYISI { get; set; }
        public Nullable<System.DateTime> ISLEM_TARIHI { get; set; }
        public Nullable<long> YENIDEN_TAKSIT { get; set; }
        public Nullable<long> unboundKUPON { get; set; }
        public Nullable<long> BANKA_POS_TAKSIT { get; set; }
        public Nullable<long> CARI_ADRES { get; set; }
        public Nullable<bool> MUHASEBELESTI { get; set; }
        public Nullable<long> TAKSIT_FISI { get; set; }
        public string BELGENO { get; set; }
        public Nullable<long> FK_PROJE { get; set; }
    
        public virtual DOVIZ_AD DOVIZ_AD1 { get; set; }
    }
}
