//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmPosKurİşlem
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOKASYON
    {
        public long ID { get; set; }
        public Nullable<long> USTID { get; set; }
        public string AD { get; set; }
        public Nullable<long> LOKASYON_TURU { get; set; }
        public Nullable<bool> SIPARIS_LOKASYONU_MU { get; set; }
        public Nullable<bool> FIZIKI_MI { get; set; }
        public Nullable<long> ILILCE { get; set; }
        public string ADRES { get; set; }
        public Nullable<bool> SICAK_SATISA_ACIK { get; set; }
        public Nullable<bool> ALISA_ACIK { get; set; }
        public Nullable<bool> SATISA_ACIK { get; set; }
        public Nullable<long> STOK_FIYAT_AD { get; set; }
        public string BOYLAM { get; set; }
        public string ENLEM { get; set; }
        public Nullable<bool> AKTIF { get; set; }
        public string EMAIL_ADRES { get; set; }
        public Nullable<int> EMAIL_PORTNO { get; set; }
        public string EMAIL_HOST { get; set; }
        public string EMAIL_USER { get; set; }
        public string EMAIL_PASSWORD { get; set; }
        public Nullable<int> YS_RestaurantList { get; set; }
        public Nullable<bool> MEKEZI_PAKET_ALIR { get; set; }
        public Nullable<long> POS_MUTFAK_YAZICI_PC { get; set; }
        public Nullable<long> MERKEZI_PAKET_PC { get; set; }
        public Nullable<bool> SSL { get; set; }
        public Nullable<int> STOK_SEVIYE_UYARISI { get; set; }
        public string ZMAIL { get; set; }
        public Nullable<int> KT_SUBE_NO { get; set; }
        public Nullable<long> LOKASYON_MALIYET_FIYAT_AD { get; set; }
        public Nullable<bool> POS_KISISAYISI_ZORUNLU { get; set; }
        public Nullable<long> AKRT_FIRMA { get; set; }
        public string AKRT_DOSYA_YOLU { get; set; }
        public Nullable<long> AKRT_DAGITICI_CARI { get; set; }
        public Nullable<long> VARSAYILAN_CARI_GRUP { get; set; }
        public Nullable<bool> E_BELGEDE_LOKASYON_ADRESI_YOLLANIR { get; set; }
        public string TELEFON { get; set; }
        public string FAX { get; set; }
        public Nullable<long> AKRT_MANUEL { get; set; }
        public string AKRT_FLEET_CODE { get; set; }
        public string PLAKA { get; set; }
        public Nullable<bool> BURDANBI_DE_CALISIR { get; set; }
        public Nullable<bool> LOKASYON_SEVKINDE_MALIYET_FIYATINI_KULLANIR { get; set; }
        public string POSTA_KODU { get; set; }
    }
}
