//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmPosKurİşlem
{
    using System;
    using System.Collections.Generic;
    
    public partial class wwwDOVIZ_KUR
    {
        public Nullable<long> DOVIZ_AD { get; set; }
        public string TARIH { get; set; }
        public decimal ALIS { get; set; }
        public decimal SATIS { get; set; }
        public Nullable<decimal> EFEKTIF_ALIS { get; set; }
        public Nullable<decimal> EFEKTIF_SATIS { get; set; }
        public long ID { get; set; }
    }
}
