//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmPosKurİşlem
{
    using System;
    using System.Collections.Generic;
    
    public partial class wwwView_Dovizlifislerdetay
    {
        public long ID { get; set; }
        public Nullable<long> Fis_id { get; set; }
        public string KOD { get; set; }
        public string BARKOD { get; set; }
        public string AD { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public string BIRIM { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<decimal> TOPLAM_KDV { get; set; }
        public Nullable<decimal> DAHIL_FIYAT { get; set; }
    }
}
