//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmPosKurİşlem
{
    using System;
    using System.Collections.Generic;
    
    public partial class wwwView_FislerinTLDegeri
    {
        public long ID { get; set; }
        public string LOKASYON { get; set; }
        public string FISTURU { get; set; }
        public Nullable<decimal> NAKIT { get; set; }
        public string DOVIZ { get; set; }
        public Nullable<decimal> TL_DEGER { get; set; }
        public Nullable<decimal> KUR_BUGUN { get; set; }
        public Nullable<decimal> KASADAKI_TL_DEGER { get; set; }
        public Nullable<decimal> TL_DEGER_FARKI { get; set; }
        public Nullable<decimal> PARAUSTU_TL { get; set; }
        public Nullable<decimal> PARAUSTU_USD { get; set; }
        public Nullable<decimal> KUR { get; set; }
        public Nullable<decimal> KUR_FARKI { get; set; }
        public Nullable<decimal> KREDI { get; set; }
        public Nullable<decimal> TOPLAM_TL { get; set; }
        public string BELGENO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ODEMETIP { get; set; }
        public Nullable<long> Dvzid { get; set; }
        public Nullable<long> Lkid { get; set; }
    }
}
